<div class="wrap wp_content_generator-about-wrap">
	<h1>WP Content Generator <?=wp_content_generator_PLUGIN_NAME_VERSION?></h1>
	<div class="wp_content_generator-about-text">
		Thank you for choosing WP Content Generator! We hope that your experience with our plugin makes creating <b>users, posts & custom posts</b> quick and easy.
	</div>
	<h2>What our plugin provides?</h2>
	<div class="wp_content_generator-about-integrations">
		<div class="wp_content_generator-feature feature-section col three-col">
			<div class="col wp_content_generator-col wp_content_generatorPanelWrapper">
				<div class="wp_content_generatorPanelHeading">Users</div>
				<div class="wp_content_generatorPanelBody">
					<p>As the name, "users" sounds like something illegal but actually its not. The main purpose of generating users is to check the functionality which is related to multiple users.</p>
					<p class="wp_content_generatorLinkWrapper">
                        <a href="#">Generate users</a>
					</p>
				</div>
			</div>
			<div class="col wp_content_generator-col wp_content_generatorPanelWrapper">
				<div class="wp_content_generatorPanelHeading">Posts/Custom Posts</div>
				<div class="wp_content_generatorPanelBody">
					<p>You can generate WordPress posts and custom posts. The purpose is again the same that it is for checking functionality like load more posts or filters etc.</p>
					<p class="wp_content_generatorLinkWrapper">
						<a href="?page=wp_content_generator-posts">Generate Posts</a>
					</p>
				</div>
			</div>
			<div class="col wp_content_generator-col wp_content_generatorPanelWrapper">
				<div class="wp_content_generatorPanelHeading">Post Generator API Key</div>
				<div class="wp_content_generatorPanelBody">
					<p>This is the key to use the Post Generator API. Ask your admin for a new API Key if you don't have one yet.</p>
					<form action="<?php echo esc_url( admin_url('admin-post.php') ); ?>" method="post">
            			<input type="hidden" name="action" value="save_wp_content_generator_api_key">
            			<input type="text" id="wp_content_generator_api_key" name="wp_content_generator_api_key" value="<?php echo esc_attr( get_option('wp_content_generator_api_key') ); ?>"/>
						<p class="wp_content_generatorLinkWrapper">
            				<input type="submit" value="Save API Key"/>
						</p>
        			</form>
				</div>
			</div>
		</div>

	</div>

	<div class="wp_content_generator-extranotes">
		<h2>Worried about deleting data generated by WP Content Generator plugin?</h2>
		<div class="wp_content_generator-wdspromos-about">
			<p>Rest assured, the process of deleting the data generated by our plugin is designed to be safe, reliable, and hassle-free. You can confidently remove all the generated content with ease and peace of mind. Our plugin ensures that the deletion process is handled smoothly, allowing you to maintain a clean and streamlined website whenever needed.</p>
			<p>
				<b>Enjoy the features of WP Content Generator!!!</b>
			</p>
		</div>		
	</div>
</div>