<?php

add_action('admin_menu', 'wp_content_generatorDashboard');

function wp_content_generatorDashboard(){
    add_menu_page( 'wp_content_generator dashboard', 'Content Generator', 'manage_options', 'wp_content_generator-dashboard', 'wp_content_generatorMainDashboard', 'dashicons-database-view', 58);
    // add_submenu_page ( 'wp_content_generator-dashboard', 'Users', 'Users', 'read', 'wp_content_generator-users', 'wp_content_generatorUsers');
    add_submenu_page ( 'wp_content_generator-dashboard', 'Posts', 'Posts', 'read', 'wp_content_generator-posts', 'wp_content_generatorPosts');
    // add_submenu_page ( 'wp_content_generator-dashboard', 'Products', 'Products', 'read', 'wp_content_generator-products', 'wp_content_generatorProducts');
    add_submenu_page ( 'wp_content_generator-dashboard', 'Tests', 'Tests', 'read', 'wp_content_generator-test', 'wp_content_generatorTest');
}

function wp_content_generatorMainDashboard(){
    include( WP_PLUGIN_DIR.'/'.plugin_dir_path(wp_content_generator_PLUGIN_BASE_URL) . 'admin/template/wp_content_generator-dashboard.php');
}

add_action('admin_bar_menu', 'wp_content_generator_add_toolbar_items', 100);

function wp_content_generator_add_toolbar_items($admin_bar){
    $admin_bar->add_menu( array(
        'id'    => 'wp_content_generatorManageDummyData',
        'title' => '<span class="ab-icon dashicons dashicons-hammer"></span>' . _( 'Manage data' ),
        'href'  => 'javascript:void(0)',
        'meta'  => array(
            'title' => __('Manage data'),            
        ),
    ));
    $admin_bar->add_menu( array(
        'id'    => 'wp_content_generatorDeletePosts',
        'parent' => 'wp_content_generatorManageDummyData',
        'title' => 'Delete Posts',
        'href'  => '#',
        'meta'  => array(
            'title' => __('Delete Posts generated by WP Content Generator '),
            'class' => 'wp_content_generatorDeletePosts wp_content_generatorDataCleaner'
        ),
    ));
    $admin_bar->add_menu( array(
        'id'    => 'wp_content_generatorDeleteThumbnails',
        'parent' => 'wp_content_generatorManageDummyData',
        'title' => 'Delete Thumbnails',
        'href'  => '#',
        'meta'  => array(
            'title' => __('Delete Thumbnails generated by WP Content Generator '),
            'class' => 'wp_content_generatorDeleteThumbnails wp_content_generatorDataCleaner'
        ),
    ));
}

function wp_content_generatorRandomDate($sStartDate, $sEndDate, $sFormat = 'Y-m-d H:i:s')
{
    $fMin = strtotime($sStartDate);
    $fMax = strtotime($sEndDate);
    $fVal = mt_rand($fMin, $fMax);
    return date($sFormat, $fVal);
}
